name: Jobs
on: 
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
jobs:
  this-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job}}]./testcontent/*.xml"
  that-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  fan-in-job:
    runs-on: ubuntu-latest
    needs: [this-job, that-job]
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"