name: Yet Another
on: 
  push:
    
jobs:
  one-more:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}]./testcontent/*.xml"
  